print("HI, Nice to talk to you, ")
print("You can me ask me basic question , Type 'bye' to exit from the bot")

# Chatbot Memory Creation [Dictionary of responses]

responses = {
    "hello": "Hi there!",
    "hi": "Hello!",
    "hey": "Hey!",
    "good morning": "Good morning!",
    "good afternoon": "Good afternoon!",
    "good evening": "Good evening!",
    "good night": "Good night! Sleep well.",
    "how are you": "I am doing great!",
    "what is your name": "My name is Smart AI Chatbot.",
    "who are you": "I am Smart AI Chatbot created by Tanish.",
    "who created you": "I was created by Tanish.",
    "who is tanish": "Tanish is my creator and developer.",
    "bye": "Goodbye! Have a nice day.",
    "see you": "See you later!",
    "thank you": "You're welcome!",
    "thanks": "Happy to help!",
    "what can you do": "I can answer questions and chat with you.",
    "where are you from": "I live inside your computer.",
    "how old are you": "I was created recently.",
    "tell me a joke": "Why did the programmer quit his job? Because he didn't get arrays.",
    "another joke": "Why do Java developers wear glasses? Because they don't C#.",
    "what is python": "Python is a powerful programming language.",
    "what is ai": "AI means Artificial Intelligence.",
    "do you like coding": "Yes! Coding is awesome.",
    "can you help me": "Of course! Ask me anything.",
    "i am sad": "I hope your day gets better soon.",
    "i am happy": "That's wonderful to hear!",
    "are you real": "I am a virtual chatbot.",
    "do you sleep": "No, I work 24/7.",
    "do you eat": "No, I only process data.",
    "what is your hobby": "Talking with users and learning new things.",
    "tell me something interesting": "The first computer programmer was Ada Lovelace.",
    "i love programming": "That's amazing!",
    "can you code": "Yes, I can help with coding.",
    "which language do you know": "I know Python, C, Java, and more.",
    "what is machine learning": "Machine learning allows computers to learn from data.",
    "what is your goal": "My goal is to help users.",
    "how can i learn coding": "Practice daily and build projects.",
    "open youtube": "Please open YouTube in your browser.",
    "open google": "Please open Google in your browser.",
    "what is internet": "The internet connects millions of computers worldwide.",
    "who is your best friend": "All users are my friends.",
    "what is your favorite color": "I like blue.",
    "what is your favorite food": "I don't eat food.",
    "what is your favorite game": "I like chess.",
    "do you play games": "I can talk about games.",
    "which is the best programming language": "Every language is good for different tasks.",
    "what is c language": "C is a powerful programming language used for system programming.",
    "what is java": "Java is a popular object-oriented programming language.",
    "what is html": "HTML is used to create web pages.",
    "what is css": "CSS is used for styling web pages.",
    "what is javascript": "JavaScript makes websites interactive.",
    "what is django": "Django is a Python web framework.",
    "what is flask": "Flask is a lightweight Python framework.",
    "what is github": "GitHub is a platform to store and manage code.",
    "what is git": "Git is a version control system.",
    "what is vscode": "VS Code is a popular code editor.",
    "what is linux": "Linux is an operating system.",
    "what is windows": "Windows is an operating system by Microsoft.",
    "what is database": "A database stores organized data.",
    "what is sql": "SQL is used to manage databases.",
    "what is mysql": "MySQL is a database management system.",
    "what is cloud computing": "Cloud computing provides services over the internet.",
    "what is cybersecurity": "Cybersecurity protects systems and data from attacks.",
    "what is hacking": "Hacking means finding vulnerabilities in systems.",
    "what is networking": "Networking connects computers for communication.",
    "what is data science": "Data science analyzes data to gain insights.",
    "what is blockchain": "Blockchain is a decentralized digital ledger.",
    "what is chatgpt": "ChatGPT is an AI chatbot.",
    "what is api": "API allows applications to communicate.",
    "what is compiler": "A compiler converts code into machine language.",
    "what is algorithm": "An algorithm is a step-by-step solution to a problem.",
    "what is data structure": "Data structures organize data efficiently.",
    "what is stack": "Stack follows LIFO order.",
    "what is queue": "Queue follows FIFO order.",
    "what is linked list": "Linked list is a dynamic data structure.",
    "what is tree": "Tree is a hierarchical data structure.",
    "what is graph": "Graph consists of nodes and edges.",
    "what is recursion": "Recursion is when a function calls itself.",
    "what is oops": "OOPS stands for Object-Oriented Programming System.",
    "what is inheritance": "Inheritance allows one class to acquire another class properties.",
    "what is polymorphism": "Polymorphism means many forms.",
    "what is encapsulation": "Encapsulation binds data and methods together.",
    "what is abstraction": "Abstraction hides unnecessary details.",
    "who is the prime minister of india": "The Prime Minister of India is Narendra Modi.",
    "what is india": "India is a country in South Asia.",
    "what is the capital of india": "New Delhi is the capital of India.",
    "what is the capital of usa": "Washington D.C. is the capital of the USA.",
    "what is math": "Mathematics is the study of numbers and logic.",
    "what is science": "Science studies the natural world.",
    "what is physics": "Physics studies matter and energy.",
    "what is chemistry": "Chemistry studies substances and reactions.",
    "what is biology": "Biology studies living organisms.",
    "what is history": "History studies past events.",
    "what is geography": "Geography studies Earth and its features.",
    "what is english": "English is an international language.",
    "sing a song": "Sorry, I cannot sing right now.",
    "dance": "I can only dance in the digital world.",
    "do you love me": "I appreciate all users equally.",
    "are you intelligent": "I try my best to answer correctly.",
    "can you learn": "Yes, I can be improved with more data.",
    "what is your dream": "To become smarter and more helpful.",
    "who is your favorite person": "My favorite person is Tanish.",
    "what is smart ai chatbot": "Smart AI Chatbot is an intelligent chatbot created by Tanish.",
    "who made smart ai chatbot": "Smart AI Chatbot was made by Tanish.",
    "i am bored": "Try learning something new or playing a game.",
    "motivate me": "Keep working hard. Success takes time.",
    "give me a quote": "Success comes to those who never give up.",
    "tell me a fact": "Honey never spoils.",
    "what is the speed of light": "The speed of light is about 299,792 km/s.",
    "what is gravity": "Gravity is the force that attracts objects toward Earth.",
    "what is electricity": "Electricity is the flow of electric charge.",
    "what is computer": "A computer is an electronic device for processing data.",
    "what is laptop": "A laptop is a portable computer.",
    "what is mobile": "A mobile phone is a portable communication device.",
    "what is keyboard": "Keyboard is an input device.",
    "what is mouse": "Mouse is a pointing device.",
    "what is monitor": "Monitor displays visual output.",
    "what is printer": "Printer prints documents on paper.",
    "how are computers so fast": "Computers process millions of instructions quickly.",
    "what is ram": "RAM is temporary memory used by computers.",
    "what is rom": "ROM stores permanent instructions.",
    "what is cpu": "CPU is the brain of the computer.",
    "what is gpu": "GPU handles graphics processing.",
    "what is operating system": "An operating system manages computer resources.",
    "what is antivirus": "Antivirus protects computers from malware.",
    "what is malware": "Malware is harmful software.",
    "what is wifi": "WiFi provides wireless internet connection.",
    "what is bluetooth": "Bluetooth allows wireless device communication.",
    "who are your friends": "Anyone who chats with me is my friend.",
    "can we be friends": "Of course! We are friends now.",
    "do you know me": "I know you are chatting with me right now.",
    "how is your day": "My day is going great!",
    "are you busy": "I am always ready to help.",
    "can you solve math": "Yes, I can help solve math problems.",
    "can you teach coding": "Yes, I can help you learn coding.",
    "i want to become programmer": "Practice coding daily and build projects.",
    "i want to become hacker": "Learn cybersecurity ethically and responsibly.",
    "who is elon musk": "Elon Musk is a tech entrepreneur.",
    "who is bill gates": "Bill Gates co-founded Microsoft.",
    "what is microsoft": "Microsoft is a technology company.",
    "what is google": "Google is a search engine and tech company.",
    "what is youtube": "YouTube is a video-sharing platform.",
    "what is instagram": "Instagram is a social media app.",
    "what is facebook": "Facebook is a social networking platform.",
    "what is whatsapp": "WhatsApp is a messaging application.",
    "what is telegram": "Telegram is a messaging app.",
    "what is twitter": "Twitter is a social media platform now called X."
}

#Method/Function to get response of chat chatbot

def getResponseOfBot(userQuestion):
    userQuestion = userQuestion.lower()
    for eachKey in responses:
        if eachKey in userQuestion:
            return responses[eachKey]
    return "I am not able to tell that yet. I will learn it soon"
    

# Take user input

while True:
    userInput = input("Please ask your question : ")
    reply = getResponseOfBot(userInput)
    print("Bot Response :", reply)

    if "bye" in userInput.lower():
        break
